version: '3'
services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - db
    stdin_open: true
    restart: always
    volumes:
      - .:/back/app
    ports:
      - 8000:8000
  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: Database
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USERNAME}"
      MYSQL_ROOT: "root"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PhpMyAdmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
networks:
  laravel-exa:
    driver: bridge
volumes:
  db:
    driver: local



